server:
  port: 80


eureka:
  client: # 客户端注册进eureka服务列表内
    service-url:
      #单机
      #defaultZone: http://localhost:7071/eureka             # 服务端地址
      #集群
      defaultZone: http://eureka7071.com:7071/eureka,http://eureka7072.com:7072/eureka,http://eureka7073.com:7073/eureka
    register-with-eureka: false    #false表示自己端就是注册中心

